-- C.List all the Degrees that are link to a student. --
SELECT DISTINCT DEGREE.D_CODE
FROM DEGREE
JOIN STUDENT
ON DEGREE.D_CODE = STUDENT.D_CODE;

-- D.List all the students that have registered for IFM2A and CSC2A. --
SELECT STUDENT.S_ID
FROM STUDENT
JOIN BRIDGE
ON STUDENT.S_ID = BRIDGE.S_ID
WHERE BRIDGE.M_CODE = 'IFM2A10' AND STUDENT.S_ID IN
	(SELECT STUDENT.S_ID
	FROM STUDENT
	JOIN BRIDGE
	ON STUDENT.S_ID = BRIDGE.S_ID
	WHERE BRIDGE.M_CODE = 'CSC2A10' );

-- E.List all the students that have registered for IFM2A or CSC2A. --
SELECT STUDENT.S_ID, BRIDGE.M_CODE
FROM STUDENT
JOIN BRIDGE
ON STUDENT.S_ID = BRIDGE.S_ID
WHERE BRIDGE.M_CODE = 'IFM2A10' OR BRIDGE.M_CODE = 'CSC2A10';

-- F.List the number of students registered for each Degree. --
SELECT DEGREE.D_CODE, COUNT(STUDENT.S_ID)
FROM STUDENT
RIGHT JOIN DEGREE
ON DEGREE.D_CODE = STUDENT.D_CODE
GROUP BY DEGREE.D_CODE;

-- G.List the average mark for each subject. --
SELECT MODULE.M_CODE, AVG(BRIDGE.MARK)
FROM MODULE
RIGHT JOIN BRIDGE
ON BRIDGE.M_CODE = MODULE.M_CODE
GROUP BY MODULE.M_CODE;

-- H.List all the degrees that have no students. --
SELECT DEGREE.D_CODE
FROM STUDENT
RIGHT JOIN DEGREE
ON DEGREE.D_CODE = STUDENT.D_CODE
GROUP BY DEGREE.D_CODE
HAVING COUNT(STUDENT.S_ID) = 0;

-- I.List the number of modules linked to each degree. --
SELECT D_CODE, COUNT(M_CODE)
FROM (SELECT DISTINCT DEGREE.D_CODE, BRIDGE.M_CODE
		FROM DEGREE
		JOIN STUDENT
		ON STUDENT.D_CODE = DEGREE.D_CODE
		JOIN BRIDGE
		ON BRIDGE.S_ID = STUDENT.S_ID) AS NT
GROUP BY D_CODE;

SELECT D_CODE, COUNT(M_CODE)
FROM (SELECT DISTINCT DEGREE.D_CODE,BRIDGE.M_CODE 
FROM DEGREE, STUDENT, BRIDGE
WHERE DEGREE.D_CODE=STUDENT.D_CODE AND STUDENT.S_ID=BRIDGE.S_ID) AS NT
GROUP BY D_CODE;